name: Checks

on: pull_request

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # available versions in package.json engine section
        node-version: ['18']
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: sudo apt-get install libimagequant-dev
      - run: yarn install
      - run: yarn lint
  # test:
  #   name: Run tests
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       # available versions in package.json engine section
  #       node-version: [ '18' ]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3.0.0

  #     - name: Setup Node.js environment
  #       uses: actions/setup-node@v3.0.0
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'yarn'
  #     - run: sudo apt-get install libimagequant-dev
  #     - run: yarn install
  #     - run: yarn test
